name: Weflo S3 Deploy
on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      
    steps: 
    - uses: actions/checkout@main
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        
    - name: Install & Build
      run: |
        npm install --legacy-peer-deps
        CI='' npm run build
        
    - name: Deploy
      run: aws s3 sync ./build s3://${{ secrets.S3_BUCKET }} --profile=weflow-a
