name: Weflo S3 Deploy
on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      
    steps: 
    - uses: actions/checkout@main
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        
    - name: Install & Build
      run: |
        npm install --legacy-peer-deps
        CI='' npm run build
        
    - name: Deploy
      uses: reggionick/s3-deploy@v4
      with:
        folder: build
        bucket: ${{ secrets.S3_BUCKET }}
        bucket-region: ${{ secrets.S3_BUCKET_REGION }}
        invalidation: /
        delete-removed: true
        no-cache: true
        private: true
